### ISSUE TITLE
LifecycleProfilerTest fails: Guice creation errors: LocatorWiring is null

### ISSUE THREAD

**Issue by hohwille** [takari/maven-profiler#11]
I forked and cloned this repo as I want to work on some feature/improvements.
Initial build without changing anything is failing with this error:
```
com.google.inject.CreationException: Guice creation errors:

1) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but io.tesla.lifecycle.profiler.LifecycleProfilerTest.sessionProfileRenderer is not @Nullable
  while locating io.tesla.lifecycle.profiler.SessionProfileRenderer
    for field at io.tesla.lifecycle.profiler.LifecycleProfilerTest.sessionProfileRenderer(Unknown Source)
  at org.eclipse.sisu.launch.InjectedTestCase$SetUpModule.configure(InjectedTestCase.java:84)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:437)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:94)
	at com.google.inject.Guice.createInjector(Guice.java:71)
	at com.google.inject.Guice.createInjector(Guice.java:61)
	at org.eclipse.sisu.launch.InjectedTestCase.setUp(InjectedTestCase.java:61)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by cstamas** [comment]
Fixed by f0f7a2c302c409fd71b81f61decf6d297f825c3f
